
equipos = [[] for _ in range(32)]
with open("../data/2023.txt") as f:
  for l in f.readlines():
    if l == '\n': break
    id, l, v, *_ = map(int, l.strip().split(' '))
    print(id, l, v)
    equipos[l].append(id)
    equipos[v].append(id)

with open("correcion.txt", "w") as f:
  for i, equipo in enumerate(equipos):
    print(f"{i} {len(equipo)}")
    f.write(' '.join(map(str, equipo)) + "\n")

equipos = [
  (0, "BUF"),
  (1, "MIA"),
  (2, "NE"),
  (3, "NYJ"),
  (4, "CIN"),
  (5, "BAL"),
  (6, "CLE"),
  (7, "PIT"),
  (8, "JAX"),
  (9, "TEN"),
  (10, "IND"),
  (11, "HOU"),
  (12, "KC"),
  (13, "LAC"),
  (14, "LV"),
  (15, "DEN"),
  (16, "PHI"),
  (17, "DAL"),
  (18, "NYG"),
  (19, "WAS"),
  (20, "MIN"),
  (21, "DET"),
  (22, "GB"),
  (23, "CHI"),
  (24, "TB"),
  (25, "CAR"),
  (26, "NO"),
  (27, "ATL"),
  (28, "SF"),
  (29, "SEA"),
  (30, "LAR"),
  (31, "ARI")]

partidos = "ARI@WSHNYGDAL@SFCIN@LAR@SEABAL@CLEATL@HOULAR@PITBYESF@CHI@PHISEAATLCARGB@DET@JAXHOUWSH@TB@TENMIN@ARIBYENO@NYJTB@CARIND@CHI@NOBALHOU@CININD@CLE@PIT@TENDET@ARISEACLECIN@LACBYELAR@JAX@SFMIAPITBUF@NYJLV@WSHMIAJAXNYG@NETB@CINDENNYJ@PHIBYE@KCDAL@LACNE@MIACAR@ATLNO@SEAMIN@DET@MIABYEHOUIND@CHIDAL@TEN@TB@NOATLGB@JAXTBCHIGB@TB@KCDEN@WSHMINLV@LAC@NOCAR@DET@MINBYEDET@CLEARIATL@GBCIN@CLEBALLAR@TEN@ARISEABYE@SFBUFHOU@BALPIT@JAXINDMIN@PIT@KCCLECLECIN@PITTENBALBYESF@IND@SEAARI@BALPIT@DEN@LARJAXCHI@HOUNYJ@CINDAL@NYGNYJ@ARINE@SF@LACBYELAR@PHINYG@CARWSHSEAPHI@BUF@MIADET@WSHDENLVWSH@MIA@CHINYJ@KCGBKCBYE@BUFMINCLE@HOU@LAC@DETNELAC@LVDET@KCSEAATL@GBCAR@TB@BALLVBYE@LACCHIGB@NO@CHIDEN@MIN@DALMINGB@CHI@ATLNODET@LVBYE@DENMINLAR@PITLAC@DETKC@NYGTB@CAR@MINCHIHOU@BALIND@JAXPIT@ATLNOBYE@CARTB@CINARIJAXDEN@NYJ@TENCLETEN@INDINDJAX@HOU@BALLARTEN@JAXCLENO@CAR@NEBYETB@TEN@CINPIT@ATLLVHOUJAX@INDKCHOUATL@BUFIND@NO@PITBYESFTEN@HOUCIN@CLEBAL@TBCAR@TENKCDET@JAXCHI@NYJ@MINDENLAC@DENMIABYEPHI@LV@GBBUF@NELVCIN@LACLV@DEN@BUFPIT@LACGBNE@CHI@DETNYGNYJ@MIAKCBYEMINLAC@KC@INDDENLAR@SEASF@CIN@INDPHIARIPIT@DAL@GBBYESEA@ARICLE@BALWSHNO@NYG@SFLACMIA@TEN@MINLVBYEDAL@KCCHI@NYJDET@GBBAL@NEDEN@LVBUF@DENKCMIA@LAC@NEDEN@BUFNYGCAR@PHINE@KCBYELV@NYJ@WSHTENNYJDAL@BALBUFMINTB@PHILAC@CARKC@CHISF@GB@ATLNO@DENCHIBYE@LV@CINDETGB@DETNEPHIMIA@NYJ@DALNO@LVBUF@MIAWSHINDBYE@NYGLAC@PITKC@DEN@BUFNYJNOTEN@CAR@GBTB@NE@HOUJAX@INDCHI@MINBYE@ATLDETCARNYG@LAR@TBATLNYGDAL@ARI@SFSEA@MIA@BUFWSHNYJ@LV@DAL@WSHNEBYEGB@NO@PHILARPHINYJBUF@DALNEKC@DENPHIBYE@NYGLAC@LV@BUFMIAATLHOU@MIAWSH@CLE@NEPHI@NEMIN@TBWSH@LAR@NYJMIA@WSHDALBYE@KCBUFSF@DAL@SEANYGARI@NYGPITSFCLE@LV@HOUBALBYE@LARJAXTENGB@CLE@CINARINE@INDCIN"

